
##### DEFINICION PERSONAJES #####


##### DEFINICION OBJETOS #####
image Cel = "gui/images/objetos/celular.png"
image CelR = "gui/images/objetos/celular_roto.png"
image Cuadro = "gui/images/objetos/cuadro.png"
image CuadroR = "gui/images/objetos/cuadro_roto.png"

##### DEFINICION ESCENARIOS #####
image HABITACION = "gui/images/escenarios/habitacion.png"
image BANO = "gui/images/escenarios/bano.png"