##### DEFINICION OBJETOS #####
image Cel = "gui/images/objetos/celular.png"
image CelR = "gui/images/objetos/celular_roto.png"
image Cuadro = "gui/images/objetos/cuadro.png"
image CuadroR = "gui/images/objetos/cuadro_roto.png"
image marimonda = "gui/images/personajes/marimonda.png"
image personas = "gui/images/escenarios/v3.png"

##### DEFINICION ESCENARIOS #####
image HABITACION = "gui/images/escenarios/habitacion.png"
image BANO = "gui/images/escenarios/bano.png"
image bg_cocina = "gui/images/escenarios/cocina.png"
image bg_bano_sangre = "gui/images/escenarios/bano-sangre.png"
image carnaval = "gui/images/escenarios/carnaval.png"
image bg_pasillo = "gui/images/escenarios/pasillo.png"
image bg_manicomio = "gui/images/escenarios/manicomio.png"
image bg_ventana = "gui/images/escenarios/ventana.png"
image bg_calle_noche = "gui/images/escenarios/ciudad-noche.png"

# FONDOS (Placeholders para los que no tienes)
# Renpy creará un fondo gris con el nombre si usas Placeholder
image bg_sala_noche = "gui/images/escenarios/cocina.png"

##### DEFINICION ENTIDAD #####

image entidad_1 = "gui/images/entidad/Entidad1"
image entidad_2 = "gui/images/entidad/Entidad2"
image entidad_3 = "gui/images/entidad/Entidad3"
image entidad_4 = "gui/images/entidad/Entidad4"
image entidad_5 = "gui/images/entidad/Entidad5"
image entidad_6 = "gui/images/entidad/Entidad6"
image entidad_7 = "gui/images/entidad/Entidad7"
image entidad_8 = "gui/images/entidad/Entidad8"
image entidad_9 = "gui/images/entidad/Entidad9"
image entidad_10 = "gui/images/entidad/Entidad10"
image entidad_11 = "gui/images/entidad/Entidad11"
image entidad_12 = "gui/images/entidad/Entidad12"
image entidad_13 = "gui/images/entidad/Entidad13"
image entidad_14 = "gui/images/entidad/Entidad14"
image entidad_15 = "gui/images/entidad/Entidad15"
image entidad_16 = "gui/images/entidad/Entidad16"
image entidad_17 = "gui/images/entidad/Entidad17"
image entidad_18 = "gui/images/entidad/Entidad18"
image entidad_19 = "gui/images/entidad/Entidad19"
image entidad_20 = "gui/images/entidad/Entidad20"
image entidad_21 = "gui/images/entidad/Entidad21"
image entidad_22 = "gui/images/entidad/Entidad22"
image entidad_23 = "gui/images/entidad/Entidad23"
image entidad_24 = "gui/images/entidad/Entidad24"
image entidad_25 = "gui/images/entidad/Entidad25"
image entidad_26 = "gui/images/entidad/Entidad26"
image entidad_27 = "gui/images/entidad/Entidad27"
image entidad_28 = "gui/images/entidad/Entidad28"
image entidad_29 = "gui/images/entidad/Entidad29"
image entidad_30 = "gui/images/entidad/Entidad30"
image entidad_31 = "gui/images/entidad/Entidad31"
image entidad_32 = "gui/images/entidad/Entidad32"
image entidad_33 = "gui/images/entidad/Entidad33"
image entidad_34 = "gui/images/entidad/Entidad34"
image entidad_35 = "gui/images/entidad/Entidad35"
image entidad_36 = "gui/images/entidad/Entidad36"
image entidad_37 = "gui/images/entidad/Entidad37"
image entidad_38 = "gui/images/entidad/Entidad38"
image entidad_39 = "gui/images/entidad/Entidad39"
image entidad_40 = "gui/images/entidad/Entidad40"
image entidad_41 = "gui/images/entidad/Entidad41"
image entidad_42 = "gui/images/entidad/Entidad42"
image entidad_43 = "gui/images/entidad/Entidad43"
image entidad_44 = "gui/images/entidad/Entidad44"
image entidad_45 = "gui/images/entidad/Entidad45"
image entidad_46 = "gui/images/entidad/Entidad46"

