##### DEFINICION OBJETOS #####
image Cel = "gui/images/objetos/celular.png"
image CelR = "gui/images/objetos/celular_roto.png"
image Cuadro = "gui/images/objetos/cuadro.png"
image CuadroR = "gui/images/objetos/cuadro_roto.png"
image marimonda = "gui/images/personajes/marimonda.png"
image personas = "gui/images/escenarios/v3.png"

##### DEFINICION ESCENARIOS #####
image HABITACION = "gui/images/escenarios/habitacion.png"
image BANO = "gui/images/escenarios/bano.png"
image bg_cocina = "gui/images/escenarios/cocina.png"
image bg_bano_sangre = "gui/images/escenarios/bano-sangre.png"
image carnaval = "gui/images/escenarios/carnaval.png"
image bg_pasillo = "gui/images/escenarios/pasillo.png"
image bg_manicomio = "gui/images/escenarios/manicomio.png"
image bg_ventana = "gui/images/escenarios/ventana.png"
image bg_calle_noche = "gui/images/escenarios/ciudad-noche.png"

# FONDOS (Placeholders para los que no tienes)
# Renpy creará un fondo gris con el nombre si usas Placeholder
image bg_sala_noche = "gui/images/escenarios/cocina.png"

##### DEFINICION ENTIDAD #####

image entidad_1 = "gui/images/entidad/Entidad1"
image entidad_2 = "gui/images/entidad/Entidad2"
image entidad_3 = "gui/images/entidad/Entidad3"
image entidad_4 = "gui/images/entidad/Entidad4"
image entidad_5 = "gui/images/entidad/Entidad5"
image entidad_6 = "gui/images/entidad/Entidad6"
image entidad_7 = "gui/images/entidad/Entidad7"
image entidad_8 = "gui/images/entidad/Entidad8"
image entidad_9 = "gui/images/entidad/Entidad9"
image entidad_10 = "gui/images/entidad/Entidad10"
image entidad_11 = "gui/images/entidad/Entidad11"
image entidad_12 = "gui/images/entidad/Entidad12"
image entidad_13 = "gui/images/entidad/Entidad13"
image entidad_14 = "gui/images/entidad/Entidad14"
image entidad_14 = "gui/images/entidad/Entidad14"
image entidad_14 = "gui/images/entidad/Entidad14"
image entidad_14 = "gui/images/entidad/Entidad14"
image entidad_14 = "gui/images/entidad/Entidad14"
image entidad_14 = "gui/images/entidad/Entidad14"
image entidad_14 = "gui/images/entidad/Entidad14"
image entidad_14 = "gui/images/entidad/Entidad14"
image entidad_14 = "gui/images/entidad/Entidad14"
image entidad_14 = "gui/images/entidad/Entidad14"
image entidad_14 = "gui/images/entidad/Entidad14"
image entidad_14 = "gui/images/entidad/Entidad14"
image entidad_14 = "gui/images/entidad/Entidad14"
image entidad_14 = "gui/images/entidad/Entidad14"
image entidad_14 = "gui/images/entidad/Entidad14"
image entidad_14 = "gui/images/entidad/Entidad14"

